import { useEffect, useState } from 'react';
import { useParams, Link, Navigate } from 'react-router-dom';
import { ArrowLeft, FileText, Video, ExternalLink, CheckCircle2, HelpCircle, Clock, BarChart3, Cpu, GraduationCap, Loader2 } from 'lucide-react';
import PlatformNav from '@/components/layout/PlatformNav';
import SEO from '@/components/ui/SEO';
import LoadingState from '@/components/ui/LoadingState';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { createNotification } from '@/lib/notifications';
import type { Project, ProjectResource, Quiz, QuizQuestion, QuizAttempt } from '@/types';
const BUCKET='alyntis-resources';
const links=[{label:'Dashboard',to:'/dashboard'},{label:'Courses',to:'/dashboard/courses'},{label:'Projects',to:'/dashboard/projects'}];
export default function StudentProjectDetail(){
 const {slug}=useParams(); const {profile}=useAuth();
 const [project,setProject]=useState<Project|null>(null),[resources,setResources]=useState<ProjectResource[]>([]),[resourceUrls,setResourceUrls]=useState<Record<string,string>>({}),[quiz,setQuiz]=useState<Quiz|null>(null),[questions,setQuestions]=useState<QuizQuestion[]>([]),[attempts,setAttempts]=useState<QuizAttempt[]>([]),[completed,setCompleted]=useState(false),[loading,setLoading]=useState(true),[answers,setAnswers]=useState<Record<string,string>>({}),[submitting,setSubmitting]=useState(false),[result,setResult]=useState<{score:number;total:number;passed:boolean}|null>(null);
 useEffect(()=>{if(!slug||!profile?.id)return; (async()=>{const {data:p,error}=await supabase.from('projects').select('*').eq('slug',slug).eq('status','published').maybeSingle();if(error||!p){setLoading(false);return;}setProject(p as Project);const [r,q,c,a]=await Promise.all([supabase.from('project_resources').select('*').eq('project_id',p.id).order('sort_order'),supabase.from('quizzes').select('*').eq('project_id',p.id).maybeSingle(),supabase.from('project_completions').select('id').eq('project_id',p.id).eq('student_id',profile.id).maybeSingle(),supabase.from('quiz_attempts').select('*').eq('student_id',profile.id).order('created_at',{ascending:false})]);const rs=(r.data as ProjectResource[])||[];setResources(rs);const urls:Record<string,string>={};await Promise.all(rs.map(async x=>{if(x.file_path){const {data}=await supabase.storage.from(BUCKET).createSignedUrl(x.file_path,3600);if(data?.signedUrl)urls[x.id]=data.signedUrl;}else if(x.url)urls[x.id]=x.url;}));setResourceUrls(urls);if(q.data){setQuiz(q.data as Quiz);const {data:qs}=await supabase.from('quiz_questions').select('*').eq('quiz_id',q.data.id).order('sort_order');setQuestions((qs as QuizQuestion[])||[]);}setCompleted(!!c.data);setAttempts((a.data as QuizAttempt[])||[]);setLoading(false);})();},[slug,profile?.id]);
 if(loading)return <><PlatformNav links={links}/><div className="min-h-screen bg-navy-950 pt-20"><LoadingState/></div></>; if(!project)return <Navigate to="/dashboard/projects" replace/>;
 const complete=async()=>{if(completed||!profile)return;const {error}=await supabase.from('project_completions').insert({project_id:project.id,student_id:profile.id});if(!error){setCompleted(true);await createNotification({type:'project_completion',student_id:profile.id,student_name:profile.full_name||profile.email,project_id:project.id,project_title:project.title});}};
 const submitQuiz=async()=>{if(!quiz||!profile||!questions.length)return;setSubmitting(true);let correct=0;questions.forEach(q=>{if(answers[q.id]===q.correct_answer)correct++;});const passed=Math.round(correct/questions.length*100)>=quiz.pass_score;const {data}=await supabase.from('quiz_attempts').insert({quiz_id:quiz.id,student_id:profile.id,answers,score:correct,total_questions:questions.length,passed}).select().single();setResult({score:correct,total:questions.length,passed});if(data)setAttempts([data as QuizAttempt,...attempts]);await createNotification({type:passed?'quiz_completion':'quiz_attempt',student_id:profile.id,student_name:profile.full_name||profile.email,quiz_id:quiz.id,quiz_title:quiz.title,project_id:project.id,project_title:project.title,score:correct,passed,total_questions:questions.length} as never);setSubmitting(false);};
 return <><SEO title={`${project.title} — Alyntis`} description={project.description||''}/><PlatformNav links={links}/><main className="min-h-screen bg-navy-950 pt-20"><div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8"><Link to="/dashboard/projects" className="inline-flex items-center gap-2 text-sm text-gray-400 hover:text-teal-400"><ArrowLeft className="h-4 w-4"/>Back to Projects</Link><div className="mt-6 grid gap-8 lg:grid-cols-2"><div><div className="flex flex-wrap gap-2">{project.class_level&&<span className="rounded-full bg-white/5 px-3 py-1 text-xs text-gray-300"><GraduationCap className="mr-1 inline h-3 w-3"/>{project.class_level}</span>}{project.difficulty&&<span className="rounded-full bg-white/5 px-3 py-1 text-xs text-gray-300"><BarChart3 className="mr-1 inline h-3 w-3"/>{project.difficulty}</span>}</div><h1 className="mt-4 text-3xl font-bold text-white">{project.title}</h1><p className="mt-3 text-gray-300">{project.description}</p>{project.estimated_time&&<p className="mt-4 text-sm text-gray-400"><Clock className="mr-1 inline h-4 w-4"/>{project.estimated_time}</p>}{project.technology&&<p className="mt-2 text-sm text-gray-400"><Cpu className="mr-1 inline h-4 w-4"/>{project.technology}</p>}</div>{project.image_url&&<img src={project.image_url} alt={project.title} className="w-full rounded-2xl border border-white/10 object-cover"/>}</div>
 {resources.length>0&&<section className="mt-10"><h2 className="text-xl font-bold text-white">Resources</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{resources.map(r=><a key={r.id} href={resourceUrls[r.id]} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-4 hover:border-teal-500/30">{r.resource_type==='pdf'?<FileText className="h-5 w-5 text-red-400"/>:<Video className="h-5 w-5 text-teal-400"/>}<span className="flex-1 text-sm font-semibold text-white">{r.title}</span><ExternalLink className="h-4 w-4 text-gray-500"/></a>)}</div></section>}
 {(['what_you_build','what_you_learn','components','build_steps','testing','troubleshooting','take_it_further'] as const).map(k=>project[k]&&<section key={k} className="mt-8"><h2 className="text-xl font-bold text-white">{k.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-gray-300">{project[k]}</p></section>)}
 {quiz&&questions.length>0&&<section className="mt-10 rounded-2xl border border-white/10 bg-white/5 p-6"><h2 className="text-xl font-bold text-white"><HelpCircle className="mr-2 inline h-5 w-5 text-teal-400"/>{quiz.title}</h2>{result&&<div className={`mt-4 rounded-xl p-4 ${result.passed?'bg-teal-500/10':'bg-red-500/10'}`}><p className="font-semibold text-white">Score: {result.score}/{result.total} {result.passed?'— Passed':'— Try again'}</p></div>}<div className="mt-5 space-y-5">{questions.map((q,i)=><div key={q.id}><p className="text-sm font-semibold text-white">{i+1}. {q.question}</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{(['a','b','c','d'] as const).map(k=><label key={k} className="cursor-pointer rounded-lg border border-white/10 p-3 text-sm text-gray-300 hover:bg-white/5"><input type="radio" name={q.id} checked={answers[q.id]===k} onChange={()=>setAnswers({...answers,[q.id]:k})} className="mr-2"/>{q[`option_${k}`]}</label>)}</div></div>)}</div><button disabled={submitting} onClick={submitQuiz} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-teal-500 px-5 py-3 text-sm font-semibold text-white">{submitting&&<Loader2 className="h-4 w-4 animate-spin"/>}Submit Quiz</button></section>}
 <div className="mt-10 flex justify-end">{completed?<span className="inline-flex items-center gap-2 rounded-xl bg-teal-500/20 px-5 py-3 text-sm font-semibold text-teal-300"><CheckCircle2 className="h-4 w-4"/>Project Completed</span>:<button onClick={complete} className="rounded-xl bg-gradient-to-r from-teal-500 to-cyan-500 px-5 py-3 text-sm font-semibold text-white">Mark Project Complete</button>}</div></div></main></>;
}
