import { useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Check, Clock3, FlaskConical, GraduationCap, Rocket, Satellite, ShieldCheck, Sparkles, Target } from 'lucide-react';
import './space-learning-phase4.css';

type Level={classes:string;title:string;description:string;topics:string[];activities:string[]};
type Module={id:string;icon:string;title:string;description:string;classes:string;difficulty:'EASY'|'MEDIUM'|'HARD';duration:string;topic:string;activityType:string;whatYouLearn:string[];activity:string;mission:string;materials:string[];outcomes:string[];safety?:string[];connected?:boolean};
type Mission={id:string;title:string;story:string;objective:string;equipment:string[];steps:string[];challenge:string;difficulty:'EASY'|'MEDIUM'|'HARD';time:string;skills:string[];outcomes:string[];connected?:boolean};
const levels:Level[]=[
{classes:'1–3',title:'SPACE EXPLORER',description:'Discover the sky, planets and the basic ideas behind space exploration.',topics:['Solar System','Sun and Moon','Planets','Stars','Basic astronomy','Rockets'],activities:['Paper rocket','Moon phases','Solar System model','Constellation activity']},
{classes:'4–5',title:'YOUNG SPACE SCIENTIST',description:'Turn curiosity into experiments with gravity, orbits, rockets and simple electronics.',topics:['Gravity','Orbits','Rockets','Spacecraft','Moon missions','Basic electronics'],activities:['Water rocket','Crater experiment','Sensor experiment','Moon habitat model']},
{classes:'6–8',title:'JUNIOR SPACE ENGINEER',description:'Build, program and test systems inspired by rovers, satellites and mission communications.',topics:['Robotics','Sensors','Motors','Programming','Mars Rover','Satellites','Communication'],activities:['Mars Rover','Sensor programming','Autonomous navigation','Satellite telemetry']},
{classes:'9–10',title:'SPACE TECHNOLOGY',description:'Explore engineering systems, telemetry, Earth observation and introductory AI.',topics:['Robotics','Satellite systems','Telemetry','Electronics','Earth observation','AI introduction'],activities:['Satellite-inspired system','Earth observation','Rover navigation','Telemetry experiment']},
{classes:'11–12',title:'ADVANCED SPACE INNOVATION',description:'Apply AI, computer vision, autonomous robotics and data analysis to space problems.',topics:['AI for Space','Computer Vision','Autonomous robotics','Satellite systems','Data analysis','Earth observation','Space communication'],activities:['AI rock classification','Rover computer vision','Satellite data analysis','Autonomous navigation']}];
const modules:Module[]=[
{id:'rocket',icon:'🚀',title:'Rocket Engineering',description:'Understand thrust, pressure, Newton’s laws and aerodynamic design through safe classroom experiments.',classes:'4–10',difficulty:'MEDIUM',duration:'60–90 min',topic:'Engineering',activityType:'Experiment',whatYouLearn:['Thrust and propulsion','Newton’s laws','Pressure','Aerodynamics'],activity:'Build and test a water or paper rocket with a controlled launch procedure.',mission:'Build a rocket that travels consistently while following the safety plan.',materials:['Paper or approved water-rocket materials','Measuring tape','Open outdoor test area','Eye protection'],outcomes:['Explain how thrust produces motion.','Identify design factors that affect flight.','Measure and compare experimental results.'],safety:['Adult supervision required.','Never point a rocket at people.','Conduct launches only in a suitable open area.']},
{id:'rover',icon:'🔴',title:'Mars Rover',description:'Learn how mobile robots sense, move and navigate uncertain terrain while operating far from Earth.',classes:'6–10',difficulty:'HARD',duration:'90 min',topic:'Robotics',activityType:'Build + Program',whatYouLearn:['Sensors','Motors','Robotics','Navigation','Programming'],activity:'Build and program a rover to navigate obstacles and locate sample sites.',mission:'Navigate a simulated Martian terrain and collect three scientific samples.',materials:['Arduino/compatible controller','DC motors','Wheels and chassis','Ultrasonic sensor','Battery','Jumper wires','Laptop'],outcomes:['Explain how sensors support robot navigation.','Program rover movement.','Interpret telemetry and solve a navigation problem.'],safety:['Handle batteries and electronics according to school laboratory procedures.','Inspect the rover before operation.'],connected:true},
{id:'satellite',icon:'🛰️',title:'Satellite Engineering',description:'Investigate how satellite-inspired systems collect measurements and communicate useful data.',classes:'6–12',difficulty:'MEDIUM',duration:'60–90 min',topic:'Satellites',activityType:'Build + Measure',whatYouLearn:['Telemetry','Sensors','Power systems','Communication'],activity:'Assemble a classroom telemetry station that records environmental readings.',mission:'Collect a clean data set and explain what each measurement tells a mission team.',materials:['Microcontroller','Temperature sensor','Light sensor','Humidity sensor','Breadboard','Laptop'],outcomes:['Identify common telemetry measurements.','Record and interpret sensor data.','Explain why reliable communication matters.']},
{id:'communication',icon:'📡',title:'Space Communication',description:'Explore how commands and scientific data travel between remote systems and mission teams.',classes:'6–12',difficulty:'MEDIUM',duration:'45–60 min',topic:'Communication',activityType:'Simulation',whatYouLearn:['Signals','Latency','Data packets','Remote operations'],activity:'Simulate a delayed command-and-response link between a rover and mission control.',mission:'Send a sequence of commands without losing mission-critical information.',materials:['Two computers or microcontrollers','Command cards'],outcomes:['Explain why communication is essential for remote robots.','Recognize delay and signal loss.','Design a reliable command sequence.']},
{id:'ai',icon:'🤖',title:'AI for Space',description:'Use age-appropriate computer-vision ideas to classify observations and support scientific decisions.',classes:'9–12',difficulty:'HARD',duration:'60–90 min',topic:'AI',activityType:'Data Lab',whatYouLearn:['Computer vision','Classification','Training data','Model evaluation'],activity:'Compare labelled rock images and discuss how training examples affect classification.',mission:'Create a simple rock-classifier concept and evaluate where it could make mistakes.',materials:['Laptop','Image dataset','Notebook or spreadsheet'],outcomes:['Describe classification in simple terms.','Identify gaps in training data.','Evaluate model results critically.']},
{id:'earth',icon:'🌍',title:'Earth Observation',description:'Use observations and data to understand our planet as a connected system.',classes:'6–12',difficulty:'MEDIUM',duration:'60 min',topic:'Earth Science',activityType:'Data Investigation',whatYouLearn:['Remote sensing','Patterns','Environmental data','Observation'],activity:'Compare simple Earth-observation data sets and identify visible patterns.',mission:'Turn observations into a short evidence-based report.',materials:['Laptop','Prepared Earth-observation data','Worksheet'],outcomes:['Distinguish observation from interpretation.','Find patterns in environmental data.','Communicate a data-backed conclusion.']},
{id:'moon',icon:'🌕',title:'Moon Base',description:'Design a sustainable lunar habitat while balancing energy, water, oxygen, food and protection.',classes:'4–12',difficulty:'HARD',duration:'60–90 min',topic:'Habitats',activityType:'Design Challenge',whatYouLearn:['Systems thinking','Resource planning','Habitat design','Trade-offs'],activity:'Design a Moon habitat and justify the systems needed to keep a crew safe.',mission:'Create a sustainable habitat plan within a limited resource budget.',materials:['Paper/cardboard','Markers','Design worksheet'],outcomes:['Identify habitat resources.','Explain engineering trade-offs.','Communicate a system design clearly.']},
{id:'astronomy',icon:'🔭',title:'Astronomy',description:'Build a foundation in observing planets, stars, lunar phases and the scale of the universe.',classes:'1–8',difficulty:'EASY',duration:'45–60 min',topic:'Astronomy',activityType:'Observation',whatYouLearn:['Planets','Stars','Moon phases','Observation'],activity:'Create a sky-observation log and model lunar phases.',mission:'Use observations to explain one changing pattern in the night sky.',materials:['Moon-phase cards','Notebook','Simple sky map'],outcomes:['Identify major Solar System objects.','Describe lunar phases.','Record observations systematically.']}];
const missions:Mission[]=[
{id:'M01',title:'MARS SAMPLE HUNT',story:'Your rover has discovered unusual geological formations. Your mission is to collect three samples and report your findings.',objective:'Collect Sample A, Sample B and Sample C.',equipment:['Mars Rover','Mission map','Telemetry display'],steps:['Inspect the terrain and identify a safe route.','Drive to each sample marker while monitoring telemetry.','Collect each sample and record the observation.','Return mission data to control and review the route.'],challenge:'Can you complete the mission using less battery and a shorter route?',difficulty:'HARD',time:'15–25 min',skills:['Robotics','Navigation','Observation','Problem solving'],outcomes:['Use rover controls purposefully.','Interpret battery and signal telemetry.','Plan and adapt a route.'],connected:true},
{id:'M02',title:'BUILD A WATER ROCKET',story:'Your engineering team must create a safe launch design and investigate what changes its flight.',objective:'Build, test and compare rocket designs.',equipment:['Approved rocket materials','Measuring tape','Safety equipment'],steps:['Sketch the rocket and predict its flight.','Build using the approved classroom procedure.','Run a supervised test.','Record distance and compare design changes.'],challenge:'Can you improve repeatability without simply making the rocket larger?',difficulty:'MEDIUM',time:'45–90 min',skills:['Physics','Engineering','Measurement'],outcomes:['Connect design choices to motion.','Use measurements to compare tests.']},
{id:'M03',title:'DESIGN A MOON BASE',story:'A small crew needs a sustainable lunar habitat. Every kilogram and every system has a purpose.',objective:'Design a habitat supporting energy, water, oxygen, food and protection.',equipment:['Design sheet','Model materials','Resource cards'],steps:['List crew needs.','Allocate limited resources.','Draw the habitat and its systems.','Present and defend the design.'],challenge:'Can you make the habitat more resilient without increasing its resource budget?',difficulty:'HARD',time:'60–90 min',skills:['Systems thinking','Design','Problem solving'],outcomes:['Recognize engineering trade-offs.','Explain how habitat systems depend on one another.']},
{id:'M04',title:'BUILD A SATELLITE',story:'Your team must design a small satellite-inspired system that gathers useful environmental data.',objective:'Build a sensor payload and define a telemetry plan.',equipment:['Microcontroller','Sensors','Breadboard','Laptop'],steps:['Select measurements.','Connect and test sensors.','Record a sample data set.','Present telemetry to mission control.'],challenge:'Can you make your data more reliable by checking for outliers and sensor errors?',difficulty:'MEDIUM',time:'60–90 min',skills:['Electronics','Telemetry','Data analysis'],outcomes:['Collect sensor data.','Explain why calibration and validation matter.']},
{id:'M05',title:'SPACE COMMUNICATION',story:'A remote mission depends on clear commands and reliable data. Your team must design the communication procedure.',objective:'Transmit a sequence of mission commands accurately.',equipment:['Command cards','Two computers or classroom stations'],steps:['Define the message format.','Introduce a simulated delay.','Send commands and acknowledge receipt.','Test the procedure with a dropped message.'],challenge:'Can you improve reliability without making every message unnecessarily long?',difficulty:'MEDIUM',time:'45–60 min',skills:['Communication','Logic','Systems thinking'],outcomes:['Explain delay and reliability.','Design a simple communication protocol.']},
{id:'M06',title:'EARTH OBSERVATION',story:'Mission control needs evidence about a changing Earth system. Your team must turn observations into a clear finding.',objective:'Analyze a prepared observation data set and report a pattern.',equipment:['Laptop','Prepared data','Worksheet'],steps:['Inspect the data.','Identify a pattern.','Check whether the pattern has enough evidence.','Write a short mission report.'],challenge:'Can you identify one limitation in your evidence?',difficulty:'MEDIUM',time:'45–60 min',skills:['Data analysis','Earth science','Communication'],outcomes:['Find patterns in data.','Separate evidence from assumptions.']},
{id:'M07',title:'AI SPACE SCIENTIST',story:'Your science team is testing whether image classification could assist with rock observations.',objective:'Evaluate a simple rock-classification workflow.',equipment:['Laptop','Prepared image set'],steps:['Inspect labelled examples.','Group images by visible features.','Compare predictions with labels.','Discuss errors and missing examples.'],challenge:'How could you improve the training data?',difficulty:'HARD',time:'60–90 min',skills:['AI','Computer vision','Critical thinking'],outcomes:['Explain the role of training data.','Identify cases where an AI model may fail.']},
{id:'M08',title:'AUTONOMOUS ROVER',story:'Your rover must make navigation decisions from sensor readings instead of receiving every movement command.',objective:'Design and test an obstacle-avoidance strategy.',equipment:['Rover','Distance sensor','Controller','Obstacle course'],steps:['Define safe-distance rules.','Program a basic response.','Test several obstacle layouts.','Record and improve failure cases.'],challenge:'Can you reduce collisions while keeping the rover efficient?',difficulty:'HARD',time:'60–90 min',skills:['Programming','Sensors','Autonomy'],outcomes:['Connect sensor readings to decisions.','Iterate on an autonomous control strategy.']}];
const stars=(d:Module['difficulty'])=>d==='EASY'?'★':d==='MEDIUM'?'★★':'★★★';
export default function SpaceLearningPhase4(){
 const[classFilter,setClassFilter]=useState('ALL'),[topicFilter,setTopicFilter]=useState('ALL'),[difficultyFilter,setDifficultyFilter]=useState('ALL'),[durationFilter,setDurationFilter]=useState('ALL');
 const[selectedModule,setSelectedModule]=useState<Module|null>(null),[selectedMission,setSelectedMission]=useState<Mission|null>(null),[selectedLevel,setSelectedLevel]=useState<Level|null>(null);
 const filtered=useMemo(()=>modules.filter(m=>(classFilter==='ALL'||m.classes.includes(classFilter))&&(topicFilter==='ALL'||m.topic===topicFilter)&&(difficultyFilter==='ALL'||m.difficulty===difficultyFilter)&&(durationFilter==='ALL'||m.duration.includes(durationFilter))),[classFilter,topicFilter,difficultyFilter,durationFilter]);
 return <section className="space-learning-phase4" aria-labelledby="space-learning-title">
  <div className="sl4-hero"><span className="sl4-label">07 // SPACE LEARNING PROGRAM</span><h2 id="space-learning-title">LEARN. BUILD. <span>EXPLORE.</span></h2><p>Space isn't something students should only read about. They should build it, program it, test it and explore it.</p></div>
  <div className="sl4-levels"><div className="sl4-section-head"><span className="sl4-label">LEARNING PATHS</span><h3>Choose your mission level.</h3><p>Age-appropriate pathways connect astronomy with hands-on engineering.</p></div><div className="sl4-level-grid">{levels.map(l=><button key={l.classes} className={`sl4-level-card ${selectedLevel?.classes===l.classes?'active':''}`} onClick={()=>setSelectedLevel(l)}><span>CLASSES {l.classes}</span><GraduationCap size={20}/><h4>{l.title}</h4><p>{l.description}</p><div>{l.topics.slice(0,4).map(t=><em key={t}>{t}</em>)}</div><small>{l.activities.length} hands-on activities <ArrowRight size={14}/></small></button>)}</div></div>
  {selectedLevel&&<div className="sl4-level-detail"><div><span className="sl4-label">CLASSES {selectedLevel.classes}</span><h3>{selectedLevel.title}</h3><p>{selectedLevel.description}</p></div><div><strong>ACTIVITY IDEAS</strong>{selectedLevel.activities.map(a=><span key={a}>✓ {a}</span>)}</div></div>}
  <div className="sl4-lab"><div className="sl4-section-head"><span className="sl4-label">08 // SPACE TECHNOLOGY LAB</span><h3>Build the knowledge behind the mission.</h3><p>Explore practical modules with a clear age range, duration, difficulty and classroom activity.</p></div><div className="sl4-filters"><select value={classFilter} onChange={e=>setClassFilter(e.target.value)} aria-label="Filter by class"><option value="ALL">All classes</option>{['1–3','4–5','6–8','9–10','11–12'].map(x=><option key={x}>{x}</option>)}</select><select value={topicFilter} onChange={e=>setTopicFilter(e.target.value)} aria-label="Filter by topic"><option value="ALL">All topics</option>{Array.from(new Set(modules.map(m=>m.topic))).map(x=><option key={x}>{x}</option>)}</select><select value={difficultyFilter} onChange={e=>setDifficultyFilter(e.target.value)} aria-label="Filter by difficulty"><option value="ALL">All difficulty</option><option value="EASY">Easy</option><option value="MEDIUM">Medium</option><option value="HARD">Hard</option></select><select value={durationFilter} onChange={e=>setDurationFilter(e.target.value)} aria-label="Filter by duration"><option value="ALL">All durations</option><option value="45–60">45–60 min</option><option value="60">60 min</option><option value="60–90">60–90 min</option><option value="90">90 min</option></select></div><div className="sl4-module-grid">{filtered.map(m=><button key={m.id} className="sl4-module-card" onClick={()=>setSelectedModule(m)}><span className="sl4-module-icon">{m.icon}</span><span className="sl4-module-meta">{m.classes} · {m.duration}</span><h4>{m.title}</h4><p>{m.description}</p><div className="sl4-module-tags"><span>{m.topic}</span><span>{stars(m.difficulty)}</span><span>{m.activityType}</span></div><small>OPEN MODULE <ArrowRight size={14}/></small></button>)}</div>{!filtered.length&&<div className="sl4-empty">No modules match these filters.</div>}</div>
  <div className="sl4-missions"><div className="sl4-section-head"><span className="sl4-label">09 // ACCEPT YOUR MISSION</span><h3>Learn by solving.</h3><p>Every mission has a story, objective, equipment list, steps, challenge and learning outcomes.</p></div><div className="sl4-mission-grid">{missions.map(m=><button key={m.id} className="sl4-mission-card" onClick={()=>setSelectedMission(m)}><div><span>{m.id}</span><span>{stars(m.difficulty)}</span></div><Target size={22}/><h4>{m.title}</h4><p>{m.story}</p><footer><span><Clock3 size={13}/> {m.time}</span><span>{m.skills.slice(0,2).join(' · ')}</span></footer><small>START MISSION <ArrowRight size={14}/></small></button>)}</div></div>
  <div className="sl4-teacher"><div className="sl4-teacher-icon"><BookOpen size={25}/></div><div><span className="sl4-label">TEACHER VIEW</span><h3>Ready-to-run activity information.</h3><p>Every module includes objectives, materials, instructions, learning outcomes and safety notes.</p></div><div className="sl4-teacher-points"><span><FlaskConical size={15}/> Materials</span><span><Clock3 size={15}/> Preparation</span><span><ShieldCheck size={15}/> Safety notes</span><span><Check size={15}/> Outcomes</span></div></div>
  <div className="sl4-knowledge"><div><span className="sl4-label">SPACE KNOWLEDGE</span><h3>Small facts. Big questions.</h3></div><div className="sl4-knowledge-grid"><article><Sparkles size={18}/><strong>DID YOU KNOW?</strong><p>Earth completes one orbit around the Sun in about 365.25 days.</p></article><article><Satellite size={18}/><strong>ENGINEERING NOTE</strong><p>Remote robots rely on sensors and telemetry to report their condition.</p></article><article><Rocket size={18}/><strong>MISSION TIP</strong><p>Good mission teams test assumptions, measure results and improve their designs.</p></article></div></div>
  {selectedModule&&<div className="sl4-modal-backdrop" onClick={()=>setSelectedModule(null)}><div className="sl4-modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="sl4-close" onClick={()=>setSelectedModule(null)} aria-label="Close module">×</button><span className="sl4-label">SPACE TECHNOLOGY LAB · {selectedModule.classes}</span><h3>{selectedModule.icon} {selectedModule.title}</h3><p>{selectedModule.description}</p><div className="sl4-detail-stats"><span><b>DIFFICULTY</b>{stars(selectedModule.difficulty)}</span><span><b>DURATION</b>{selectedModule.duration}</span><span><b>ACTIVITY</b>{selectedModule.activityType}</span></div><div className="sl4-detail-grid"><section><h4>WHAT YOU’LL LEARN</h4><ul>{selectedModule.whatYouLearn.map(x=><li key={x}>{x}</li>)}</ul><h4>HANDS-ON ACTIVITY</h4><p>{selectedModule.activity}</p><h4>MISSION</h4><p>{selectedModule.mission}</p></section><section><h4>MATERIALS</h4><ul>{selectedModule.materials.map(x=><li key={x}>{x}</li>)}</ul>{selectedModule.safety&&<><h4>SAFETY NOTES</h4><ul>{selectedModule.safety.map(x=><li key={x}>{x}</li>)}</ul></>}<h4>LEARNING OUTCOMES</h4><ul>{selectedModule.outcomes.map(x=><li key={x}>{x}</li>)}</ul></section></div>{selectedModule.connected&&<a className="sl4-modal-action" href="#mars-mission">OPEN MARS ROVER MISSION <ArrowRight size={16}/></a>}</div></div>}
  {selectedMission&&<div className="sl4-modal-backdrop" onClick={()=>setSelectedMission(null)}><div className="sl4-modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="sl4-close" onClick={()=>setSelectedMission(null)} aria-label="Close mission">×</button><span className="sl4-label">MISSION BRIEFING · {selectedMission.id}</span><h3>{selectedMission.title}</h3><p>{selectedMission.story}</p><div className="sl4-briefing"><span><b>OBJECTIVE</b>{selectedMission.objective}</span><span><b>TIME</b>{selectedMission.time}</span><span><b>DIFFICULTY</b>{stars(selectedMission.difficulty)}</span></div><div className="sl4-detail-grid"><section><h4>EQUIPMENT</h4><ul>{selectedMission.equipment.map(x=><li key={x}>{x}</li>)}</ul><h4>MISSION INSTRUCTIONS</h4><ol>{selectedMission.steps.map((x,i)=><li key={x}><b>STEP {i+1}</b>{x}</li>)}</ol></section><section><h4>SKILLS</h4><ul>{selectedMission.skills.map(x=><li key={x}>{x}</li>)}</ul><h4>MISSION CHALLENGE</h4><p>{selectedMission.challenge}</p><h4>LEARNING OUTCOMES</h4><ul>{selectedMission.outcomes.map(x=><li key={x}>{x}</li>)}</ul></section></div>{selectedMission.connected&&<a className="sl4-modal-action" href="#mars-mission">BEGIN MARS ROVER MISSION <ArrowRight size={16}/></a>}</div></div>}
 </section>;
}
