-- Seed a starter curriculum for Classes 1–12.
-- Idempotent by unique course/project slugs.

INSERT INTO courses (title, slug, description, status, sort_order)
VALUES
('Class 1 — Young Makers', 'class-1-young-makers', 'A gentle introduction to making, mechanisms, observation and creative problem solving.', 'available', 1),
('Class 2 — Exploring Machines', 'class-2-exploring-machines', 'Explore motion, gears, simple machines and the basics of mechanical design.', 'available', 2),
('Class 3 — Electronics Foundations', 'class-3-electronics-foundations', 'Build confidence with circuits, LEDs, switches and simple sensors.', 'available', 3),
('Class 4 — Sensors & Smart Systems', 'class-4-sensors-smart-systems', 'Discover sensors and create simple systems that respond to their surroundings.', 'available', 4),
('Class 5 — Arduino Foundations', 'class-5-arduino-foundations', 'Learn programming and electronics together using Arduino-based builds.', 'available', 5),
('Class 6 — Robotics & Automation', 'class-6-robotics-automation', 'Combine sensors, motors and code to design useful automated systems.', 'available', 6),
('Class 7 — IoT & Connected Devices', 'class-7-iot-connected-devices', 'Connect sensors and devices to build practical Internet of Things solutions.', 'available', 7),
('Class 8 — Advanced Robotics', 'class-8-advanced-robotics', 'Develop stronger robotics, control and problem-solving skills through autonomous builds.', 'available', 8),
('Class 9 — AI & Computer Vision', 'class-9-ai-computer-vision', 'Understand AI fundamentals and apply computer vision to real-world problems.', 'available', 9),
('Class 10 — AI, IoT & Smart Applications', 'class-10-ai-iot-smart-applications', 'Integrate AI, sensors and connected systems into practical smart applications.', 'available', 10),
('Class 11 — Drones & Autonomous Systems', 'class-11-drones-autonomous-systems', 'Explore drone technology, telemetry, autonomous navigation and engineering design.', 'available', 11),
('Class 12 — Engineering & Innovation', 'class-12-engineering-innovation', 'Turn ideas into engineered prototypes using AI, robotics, IoT, drones and 3D printing.', 'available', 12)
ON CONFLICT (slug) DO NOTHING;

WITH curriculum AS (
  SELECT * FROM (VALUES
    ('class-1-young-makers', 'Build a Mechanical Linkage', 'linkage-mechanism-class-1', 'Build and explore a simple linkage that converts one motion into another.', 'Beginner', '60 minutes', 'Mechanical Design', 'Assemble a simple linkage and observe how connected parts move together.', 'Learn observation, sequencing, basic mechanisms and cause-and-effect.', 'Linkage kit, craft materials', 'Connect the linkage pieces according to the guide. Move the input arm slowly and observe the output motion. Modify one connection and compare the result.', 'Check that joints move freely and are not over-tightened.', 'Try creating a second linkage with a different connection point.'),
    ('class-1-young-makers', 'Design a Moving Toy', 'moving-toy-class-1', 'Create a simple moving toy while learning to plan, assemble and improve a design.', 'Beginner', '90 minutes', 'Making & Mechanisms', 'Design and assemble a small mechanical toy from classroom-safe components.', 'Learn planning, assembly, creativity and iterative improvement.', 'Cardboard, wheels, axles, connectors', 'Sketch the idea. Select components. Assemble the body and moving parts. Test the motion. Make one improvement.', 'Ensure wheels and axles are aligned and the body is stable.', 'Add a new movement or decorative mechanism.'),
    ('class-2-exploring-machines', 'Build a Gear System', 'gear-system-class-2', 'Explore how gears transfer motion and change speed or direction.', 'Beginner', '75 minutes', 'Mechanical Systems', 'Build a small gear train and observe how the gears influence one another.', 'Learn rotation, direction, speed and simple mechanical relationships.', 'Gear kit, axles, base plate', 'Place the first gear on the input axle. Add a second gear so the teeth mesh. Rotate the input and observe the output. Test different gear sizes.', 'Gears should mesh without excessive pressure and rotate freely.', 'Design a three-gear transmission and predict its direction of rotation.'),
    ('class-2-exploring-machines', 'Mini Conveyor System', 'mini-conveyor-class-2', 'Build a simple conveyor mechanism and investigate continuous motion.', 'Beginner', '90 minutes', 'Automation', 'Create a tabletop conveyor that moves lightweight objects.', 'Learn motion transfer, sequencing and basic automation concepts.', 'Motor, belt, rollers, battery pack, base', 'Assemble rollers. Fit the belt. Connect the motor. Test the conveyor with a lightweight object. Adjust alignment.', 'Check belt tension and roller alignment before powering the motor.', 'Add a stop point or simple sorting mechanism.'),
    ('class-3-electronics-foundations', 'LED Circuit Lab', 'led-circuit-class-3', 'Learn the basics of an electrical circuit by building and testing an LED circuit.', 'Beginner', '60 minutes', 'Electronics', 'Build a safe low-voltage LED circuit using a resistor and power source.', 'Understand current flow, polarity, resistance and complete circuits.', 'LED, resistor, battery pack, breadboard, jumper wires', 'Place the resistor and LED on the breadboard. Connect power with correct polarity. Test the circuit. Change the resistor and observe brightness.', 'If the LED does not light, check polarity and every connection.', 'Build a two-LED circuit with independent switches.'),
    ('class-3-electronics-foundations', 'Switch-Controlled Light', 'switch-controlled-light-class-3', 'Use a switch to control an electronic output.', 'Beginner', '60 minutes', 'Electronics', 'Create a light that turns on and off with a push button or switch.', 'Learn inputs, outputs and simple control logic.', 'LED, resistor, switch, battery pack, breadboard', 'Build the LED circuit. Add the switch in series. Test open and closed states. Improve the layout.', 'Make sure connections are secure and the power source is low voltage.', 'Add a second switch and experiment with different control arrangements.'),
    ('class-4-sensors-smart-systems', 'Automatic Night Lamp', 'automatic-night-lamp-class-4', 'Create a light that responds automatically to surrounding light levels.', 'Beginner', '90 minutes', 'Sensors & Electronics', 'Build a basic light-sensitive system using an LDR and LED.', 'Understand sensors, analog changes and automatic responses.', 'LDR, LED, resistor, transistor or controller, breadboard, battery pack', 'Connect the LDR sensing circuit. Add the LED output. Test in bright and dark conditions. Tune the response.', 'Check sensor placement and verify the circuit uses a suitable resistor value.', 'Add a manual override switch.'),
    ('class-4-sensors-smart-systems', 'Smart Waste Bin', 'smart-waste-bin-class-4', 'Explore how distance sensing can make a familiar object respond automatically.', 'Beginner', '120 minutes', 'Sensors & Automation', 'Build a prototype bin lid that responds to a nearby object.', 'Learn distance sensing, actuator control and automation.', 'Ultrasonic sensor, servo motor, microcontroller, jumper wires', 'Mount the sensor. Connect the servo. Program a distance threshold. Test hand detection. Adjust the threshold and movement.', 'Check servo power and ensure the lid can move freely.', 'Add a full-bin indicator using an LED.'),
    ('class-5-arduino-foundations', 'Arduino Traffic Signal', 'arduino-traffic-signal-class-5', 'Program a realistic traffic-light sequence using Arduino.', 'Beginner', '90 minutes', 'Arduino & Coding', 'Build and program a three-light traffic signal.', 'Learn digital outputs, timing, sequencing and basic embedded programming.', 'Arduino Uno, red/yellow/green LEDs, resistors, breadboard, jumper wires', 'Wire the LEDs. Create a sequence in code. Upload the program. Test timing. Refine the cycle.', 'Check LED polarity and resistor connections before powering the board.', 'Add a pedestrian crossing button.'),
    ('class-5-arduino-foundations', 'Digital Temperature Monitor', 'arduino-temperature-monitor-class-5', 'Read temperature data from a sensor and display a useful result.', 'Beginner', '120 minutes', 'Arduino & Sensors', 'Build a temperature monitoring prototype.', 'Learn sensor input, variables, serial output and interpreting data.', 'Arduino Uno, temperature sensor, display or serial monitor, jumper wires', 'Connect the sensor. Read its value in code. Convert it into temperature. Display the reading. Test under different conditions.', 'Verify sensor wiring and library/setup requirements.', 'Add an alert when temperature crosses a chosen threshold.'),
    ('class-6-robotics-automation', 'Automated Barrier', 'automated-barrier-class-6', 'Build a model barrier that opens when a vehicle or object is detected.', 'Intermediate', '150 minutes', 'Robotics & Automation', 'Create an automated gate using a sensor and servo motor.', 'Learn sensor-triggered control, servo movement and event-based programming.', 'Arduino, ultrasonic or IR sensor, servo motor, LEDs, breadboard', 'Build the barrier. Connect the sensor and servo. Program detection and opening. Add a closing delay. Test repeatedly.', 'Ensure the servo has adequate power and the mechanism does not jam.', 'Add red/green status lights and an entry counter.'),
    ('class-6-robotics-automation', 'Robotic Arm Prototype', 'robotic-arm-class-6', 'Explore robotic movement by controlling multiple servo joints.', 'Intermediate', '180 minutes', 'Robotics & Servo Control', 'Assemble and control a small multi-joint robotic arm.', 'Learn degrees of freedom, servo control, coordinate thinking and mechanical stability.', 'Servo motors, arm structure, Arduino, external 5V supply', 'Assemble the joints. Connect servos. Program individual movements. Combine movements into a sequence. Test the arm with a light object.', 'Use an appropriate external supply and keep servo movement within mechanical limits.', 'Create a repeatable pick-and-place sequence.'),
    ('class-7-iot-connected-devices', 'IoT Weather Station', 'iot-weather-station-class-7', 'Collect environmental readings and publish them as a connected dashboard.', 'Intermediate', '180 minutes', 'IoT & Sensors', 'Build a connected weather-monitoring prototype.', 'Learn sensor data, networking, APIs and basic dashboards.', 'ESP8266/ESP32, temperature/humidity sensor, Wi-Fi, dashboard service', 'Connect sensors. Read values. Connect the board to Wi-Fi. Send data to a dashboard. Validate readings.', 'Check Wi-Fi credentials and sensor pin configuration.', 'Add historical charts and an alert for unusual readings.'),
    ('class-7-iot-connected-devices', 'Smart Room Controller', 'smart-room-controller-class-7', 'Build a connected room model that monitors and controls devices.', 'Intermediate', '180 minutes', 'IoT & Automation', 'Create a prototype for connected lighting or appliance control.', 'Learn IoT architecture, digital control and responsible automation.', 'ESP32/ESP8266, relay module or LEDs, sensors, breadboard', 'Build the room model. Add sensors. Connect outputs. Create a simple web or IoT control interface. Test manual and automatic modes.', 'Use low-voltage LED loads for classroom prototypes and verify wiring carefully.', 'Add occupancy-based automation.'),
    ('class-8-advanced-robotics', 'Robo Soccer', 'robo-soccer-class-8', 'Engineer a robot that can navigate a playing field and interact with a lightweight ball.', 'Advanced', '240 minutes', 'Robotics', 'Build and program a mobile robot for a structured challenge.', 'Learn motor control, sensor integration, strategy and iterative testing.', 'Robot chassis, motors, motor driver, controller, sensors, battery', 'Assemble the chassis. Test motor directions. Integrate sensors. Implement movement logic. Test on the field and tune behavior.', 'Check motor polarity, battery voltage and wheel alignment.', 'Add autonomous ball detection or improved navigation.'),
    ('class-8-advanced-robotics', 'Maze Solver', 'maze-solver-class-8', 'Develop a robot that can detect walls and navigate a maze.', 'Advanced', '240 minutes', 'Robotics & Sensors', 'Build a sensor-driven maze navigation robot.', 'Learn feedback, decision logic, calibration and autonomous navigation.', 'Robot chassis, motors, motor driver, IR/ultrasonic sensors, controller', 'Build the robot. Calibrate sensors. Implement wall detection. Test turns. Run repeated trials and improve the algorithm.', 'Calibrate sensors on the actual maze surface and reduce mechanical drift.', 'Compare left-hand, right-hand and sensor-based strategies.'),
    ('class-9-ai-computer-vision', 'AI Object Detector', 'ai-object-detector-class-9', 'Understand how computer vision models identify objects in images.', 'Advanced', '240 minutes', 'AI & Computer Vision', 'Create a simple object-detection application using a prepared model.', 'Learn datasets, inference, confidence scores and responsible AI basics.', 'Computer, Python, camera or sample images, object-detection model', 'Load a trained model. Run inference on sample images. Display detections. Test different scenes. Record observations.', 'Use a supported model/environment and verify image input dimensions.', 'Collect a small labelled dataset and evaluate model performance.'),
    ('class-9-ai-computer-vision', 'Vision-Based Counter', 'vision-counter-class-9', 'Use computer vision to count objects in a controlled scene.', 'Advanced', '240 minutes', 'AI & Computer Vision', 'Build a prototype that detects and counts selected objects.', 'Learn detection pipelines, counting logic and evaluation.', 'Computer, Python, camera, object-detection model', 'Define the target object. Run detection. Track or count detections. Test with different object arrangements. Measure errors.', 'Avoid double counting by testing stable and moving scenes separately.', 'Add time-based analytics and a simple dashboard.'),
    ('class-10-ai-iot-smart-applications', 'Smart Agriculture Monitor', 'smart-agriculture-monitor-class-10', 'Combine environmental sensors and IoT to monitor plant-growing conditions.', 'Advanced', '240 minutes', 'AI, IoT & Sensors', 'Build a connected agriculture-monitoring prototype.', 'Learn sensor fusion, thresholds, dashboards and data-driven decision making.', 'ESP32, soil-moisture sensor, temperature/humidity sensor, light sensor, dashboard', 'Connect sensors. Calibrate readings. Send data to a dashboard. Define thresholds. Test automatic alerts.', 'Calibrate each sensor for the chosen environment and avoid overwatering test plants.', 'Use collected data to build a simple prediction or recommendation model.'),
    ('class-10-ai-iot-smart-applications', 'AI Safety Monitor', 'ai-safety-monitor-class-10', 'Explore a computer-vision system that detects a defined safety condition.', 'Advanced', '300 minutes', 'AI & Computer Vision', 'Prototype an AI-assisted monitoring workflow using recorded or controlled camera input.', 'Learn detection, alerts, false positives and responsible deployment considerations.', 'Computer, Python, camera/sample video, detection model', 'Define the safety condition. Prepare test media. Run detection. Trigger a local alert. Review false positives and improve thresholds.', 'Use controlled classroom data and avoid collecting unnecessary personal information.', 'Add event logging and a dashboard for review.'),
    ('class-11-drones-autonomous-systems', 'Drone Telemetry System', 'drone-telemetry-class-11', 'Understand how flight controllers and ground systems exchange telemetry data.', 'Advanced', '300 minutes', 'Drones & Embedded Systems', 'Explore a simulated or controlled telemetry workflow for an unmanned system.', 'Learn telemetry concepts, flight data, communication links and system monitoring.', 'Flight controller or simulator, telemetry radio/network link, ground-control software', 'Set up the controller or simulator. Establish telemetry. Inspect flight data. Configure basic monitoring fields. Document observations.', 'Follow safe lab procedures and use simulation where flight testing is not appropriate.', 'Create a dashboard or logging workflow for telemetry data.'),
    ('class-11-drones-autonomous-systems', 'Autonomous Navigation Concept', 'autonomous-navigation-class-11', 'Design the logic behind waypoint-based autonomous navigation.', 'Advanced', '300 minutes', 'Drones & Autonomous Systems', 'Model a navigation system that plans and follows a sequence of waypoints.', 'Learn coordinates, waypoints, state machines and autonomous decision logic.', 'Drone simulator or robotics simulator, mission-planning software', 'Define a safe virtual environment. Create waypoints. Simulate the mission. Observe state transitions. Refine the route.', 'Keep the project simulation-first unless an appropriately supervised flight environment is available.', 'Add obstacle-aware route planning in simulation.'),
    ('class-12-engineering-innovation', '3D-Printed Engineering Prototype', '3d-printed-engineering-prototype-class-12', 'Take a digital design through slicing, printing, testing and iteration.', 'Advanced', '300 minutes', '3D Printing & Product Design', 'Design and manufacture a functional prototype component.', 'Learn CAD, tolerances, slicing, additive manufacturing and engineering iteration.', '3D printer, filament, CAD software, slicing software, measuring tools', 'Define the problem. Model the part. Check dimensions. Slice the model. Print the prototype. Test fit/function. Revise and reprint.', 'Verify printer settings, bed adhesion, dimensions and moving-part clearances.', 'Integrate the printed part into a robot, drone or IoT enclosure.'),
    ('class-12-engineering-innovation', 'Autonomous Systems Capstone', 'autonomous-systems-capstone-class-12', 'Integrate software, electronics and intelligent control into a documented engineering capstone.', 'Advanced', '480 minutes', 'Robotics, AI & Embedded Systems', 'Develop a prototype around a clearly defined real-world problem.', 'Learn requirements, system architecture, integration, testing and technical documentation.', 'Selected sensors, controller, actuators, software tools and prototype materials', 'Define requirements. Design the system architecture. Build subsystems. Integrate them. Test against requirements. Document results and improvements.', 'Test each subsystem independently before full integration and maintain a clear wiring/software record.', 'Prepare a demonstration, technical report and future-development roadmap.')
  ) AS t(course_slug, title, slug, description, difficulty, estimated_time, technology, what_you_build, what_you_learn, components, build_steps, troubleshooting, take_it_further)
)
INSERT INTO projects (course_id, title, slug, description, class_level, difficulty, estimated_time, technology, what_you_build, what_you_learn, components, build_steps, troubleshooting, take_it_further, status, sort_order)
SELECT c.id, curriculum.title, curriculum.slug, curriculum.description,
       replace(split_part(c.title, '—', 1), 'Class ', ''), curriculum.difficulty, curriculum.estimated_time, curriculum.technology,
       curriculum.what_you_build, curriculum.what_you_learn, curriculum.components, curriculum.build_steps, curriculum.troubleshooting, curriculum.take_it_further,
       'published', row_number() OVER (PARTITION BY c.id ORDER BY curriculum.slug)
FROM curriculum
JOIN courses c ON c.slug = curriculum.course_slug
ON CONFLICT (slug) DO NOTHING;
