-- AI / ML curriculum for Alyntis
-- Adds three standalone AI/ML courses, six hands-on projects, and curated official learning resources.

insert into public.courses (title, slug, description, image_url, status, sort_order, class_level)
values
('AI Foundations & Problem Solving','ai-foundations-problem-solving','Learn how artificial intelligence works, how to frame real-world problems for AI, and how to build simple data-driven solutions through hands-on activities.','https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=1200','available',40,null),
('Machine Learning with Python','machine-learning-with-python','Build practical machine learning models with Python. Explore datasets, regression, classification, evaluation, overfitting and responsible model development.','https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1200','available',41,null),
('Computer Vision & Edge AI','computer-vision-edge-ai','Build computer vision applications that can understand images and video, then explore real-time object detection and deployment on edge devices.','https://images.pexels.com/photos/8386422/pexels-photo-8386422.jpeg?auto=compress&cs=tinysrgb&w=1200','available',42,null)
on conflict (slug) do update set description=excluded.description,image_url=excluded.image_url,status=excluded.status;

insert into public.projects (course_id,title,slug,description,image_url,class_level,difficulty,estimated_time,technology,what_you_build,what_you_learn,components,build_steps,testing,troubleshooting,take_it_further,status,sort_order) values
((select id from courses where slug='ai-foundations-problem-solving'),'AI Problem Framing Lab','ai-problem-framing-lab','Turn a real-world school or community problem into a clear AI problem statement and design a simple data-to-decision workflow.','https://images.pexels.com/photos/3861964/pexels-photo-3861964.jpeg?auto=compress&cs=tinysrgb&w=1200','9','Beginner','2–3 hours','AI, Python, Data Thinking','A documented AI solution concept with a small sample dataset and decision flow.','Problem framing, features vs labels, data quality, training vs inference, and responsible AI thinking.','Laptop, Python or Google Colab, sample CSV dataset, notebook.','Define the problem; identify inputs and outputs; collect or create a small dataset; inspect the data; sketch an AI workflow; present the proposed solution.','Check that every input has a clear purpose and that the proposed output can be evaluated with a measurable criterion.','If the problem is too broad, narrow it to one prediction or classification task; remove columns that leak the answer.','Turn the concept into a working scikit-learn model and compare two approaches.','published',1),
((select id from courses where slug='ai-foundations-problem-solving'),'Smart Image Classifier','smart-image-classifier','Create a beginner-friendly image classification prototype that learns to distinguish two categories of objects.','https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1200','9','Intermediate','4–6 hours','Python, TensorFlow, Computer Vision','An image classifier trained on a small two-class dataset.','Image datasets, labels, train/test splits, model training, accuracy and prediction confidence.','Laptop, Google Colab, image dataset, TensorFlow/Keras.','Collect labeled images; split the dataset; preprocess images; train a small model; evaluate it; test new images; document errors.','Evaluate on images the model did not see during training and record correct and incorrect predictions.','Add more varied examples if the model memorizes backgrounds; keep class counts reasonably balanced.','Add a third class or deploy the model in a simple web interface.','published',2),
((select id from courses where slug='machine-learning-with-python'),'House Price Predictor','house-price-predictor','Build a regression model that predicts a house price from a small set of numerical and categorical features.','https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200','10','Intermediate','4–5 hours','Python, Pandas, scikit-learn','A regression notebook with predictions and evaluation metrics.','Features and targets, preprocessing, train/test splits, regression, MAE and model comparison.','Laptop, Google Colab, CSV dataset, Pandas, scikit-learn.','Load the dataset; clean missing values; select features; split the data; train a regression model; evaluate MAE; inspect prediction errors.','Compare predicted and actual values on the held-out test set and calculate an error metric.','Check data types and missing values; scale or encode features when required by the chosen model.','Compare linear regression with a tree-based model and explain the difference.','published',1),
((select id from courses where slug='machine-learning-with-python'),'Student Performance Predictor','student-performance-predictor','Explore a small educational dataset and build a classification model that predicts whether a student is likely to meet a defined performance threshold.','https://images.pexels.com/photos/5212700/pexels-photo-5212700.jpeg?auto=compress&cs=tinysrgb&w=1200','10','Intermediate','4–6 hours','Python, Pandas, scikit-learn','A classification model with an evaluation report and feature analysis.','Classification, precision, recall, confusion matrices, feature selection and responsible interpretation.','Laptop, CSV dataset, Google Colab, Pandas, scikit-learn.','Define the target carefully; inspect and clean the dataset; split the data; train a classifier; evaluate precision and recall; inspect mistakes; document limitations.','Use a held-out test set and inspect false positives and false negatives rather than relying only on accuracy.','Check class imbalance and avoid using features that directly reveal the target.','Compare two classifiers and add a simple dashboard showing predictions and metrics.','published',2),
((select id from courses where slug='computer-vision-edge-ai'),'YOLO Object Detector','yolo-object-detector','Use a pretrained YOLO model to detect objects in images or video and understand the complete computer-vision inference workflow.','https://images.pexels.com/photos/8438918/pexels-photo-8438918.jpeg?auto=compress&cs=tinysrgb&w=1200','11','Advanced','5–7 hours','Python, Ultralytics YOLO, Computer Vision','A real-time object detection demo with labeled bounding boxes.','Object detection, confidence scores, datasets, inference, evaluation and model deployment concepts.','Laptop, Python, Ultralytics, webcam or sample video.','Install the library; load a pretrained model; run inference on images; test webcam or video input; inspect confidence scores; document failure cases.','Test on different lighting, distances and object sizes and record missed or incorrect detections.','Adjust the confidence threshold carefully; check image resolution and model/task compatibility.','Collect a small custom dataset and fine-tune a model for a school-specific use case.','published',1),
((select id from courses where slug='computer-vision-edge-ai'),'Edge AI Vision Counter','edge-ai-vision-counter','Build a vision-based people or object counter that processes a camera stream and demonstrates how AI can move from a cloud notebook toward edge deployment.','https://images.pexels.com/photos/8438919/pexels-photo-8438919.jpeg?auto=compress&cs=tinysrgb&w=1200','12','Advanced','6–8 hours','Python, YOLO, OpenCV, Edge AI','A camera-based counting prototype with an inference loop and simple metrics.','Object tracking concepts, frame processing, inference latency, accuracy trade-offs and edge deployment.','Laptop, webcam, Python, OpenCV, Ultralytics YOLO.','Capture a video stream; run object detection; define a counting region; track detections across frames; calculate counts; measure approximate inference speed.','Test different scenes and verify counts manually against recorded video.','Reduce image size for speed, filter low-confidence detections, and check camera permissions.','Export the model and evaluate an edge target such as a Raspberry Pi or other supported accelerator.','published',2);

insert into public.course_resources (course_id,title,description,category,url,resource_type,sort_order) values
((select id from courses where slug='ai-foundations-problem-solving'),'Google Introduction to Machine Learning','A short official introduction to core machine-learning ideas and terminology.','Learning','https://developers.google.com/machine-learning/intro-to-ml','pdf',1),
((select id from courses where slug='ai-foundations-problem-solving'),'Google Machine Learning Crash Course','Hands-on modules covering regression, classification, datasets, neural networks, LLM basics and responsible ML.','Learning','https://developers.google.com/machine-learning/crash-course','pdf',2),
((select id from courses where slug='ai-foundations-problem-solving'),'Google ML Exercises','Interactive exercises that reinforce regression, classification, overfitting, neural networks and other ML concepts.','Practice','https://developers.google.com/machine-learning/crash-course/exercises','pdf',3),
((select id from courses where slug='machine-learning-with-python'),'Google Machine Learning Crash Course','A practical foundation for regression, classification, data preparation, neural networks and evaluation.','Learning','https://developers.google.com/machine-learning/crash-course','pdf',1),
((select id from courses where slug='machine-learning-with-python'),'TensorFlow Machine Learning Tutorials','Official tutorials with beginner and advanced notebooks that can run in Google Colab.','Learning','https://www.tensorflow.org/tutorials','pdf',2),
((select id from courses where slug='machine-learning-with-python'),'TensorFlow ML Education Path','Curated learning paths covering coding, mathematics, ML theory and hands-on projects.','Learning','https://www.tensorflow.org/resources/learn-ml','pdf',3),
((select id from courses where slug='computer-vision-edge-ai'),'Ultralytics YOLO Documentation','Official documentation for training, validating, predicting and deploying YOLO computer-vision models.','Reference','https://docs.ultralytics.com/','pdf',1),
((select id from courses where slug='computer-vision-edge-ai'),'YOLO Object Detection Guide','Official reference for object detection, custom datasets, evaluation and inference.','Reference','https://docs.ultralytics.com/tasks/detect/','pdf',2),
((select id from courses where slug='computer-vision-edge-ai'),'Ultralytics How-To Guides','Project-oriented guides covering data preparation, training, evaluation, deployment and edge hardware.','Practice','https://docs.ultralytics.com/guides/','pdf',3);
