-- Starter class-wise curriculum for the Alyntis learning platform.
-- Safe to re-run: unique slugs prevent duplicate records.

ALTER TABLE courses ADD COLUMN IF NOT EXISTS class_level text;
CREATE INDEX IF NOT EXISTS idx_courses_class_level ON courses(class_level);

INSERT INTO courses (title, slug, description, class_level, status, sort_order)
VALUES
('Class 1 — Young Makers', 'class-1-young-makers', 'Explore making, simple mechanisms and creative problem solving through hands-on activities.', '1', 'available', 1),
('Class 2 — Exploring Machines', 'class-2-exploring-machines', 'Discover gears, motion and simple machines through guided builds.', '2', 'available', 2),
('Class 3 — Electronics Foundations', 'class-3-electronics-foundations', 'Learn circuits, LEDs, switches and the foundations of electronics.', '3', 'available', 3),
('Class 4 — Sensors & Smart Systems', 'class-4-sensors-smart-systems', 'Use sensors and simple control systems to make responsive devices.', '4', 'available', 4),
('Class 5 — Arduino Foundations', 'class-5-arduino-foundations', 'Combine coding and electronics with introductory Arduino projects.', '5', 'available', 5),
('Class 6 — Robotics & Automation', 'class-6-robotics-automation', 'Build sensor-driven robotic and automated systems.', '6', 'available', 6),
('Class 7 — IoT & Connected Devices', 'class-7-iot-connected-devices', 'Connect sensors and devices to the internet and visualize useful data.', '7', 'available', 7),
('Class 8 — Advanced Robotics', 'class-8-advanced-robotics', 'Develop autonomous robots using sensors, motors and control logic.', '8', 'available', 8),
('Class 9 — AI & Computer Vision', 'class-9-ai-computer-vision', 'Explore AI inference, datasets and computer vision applications.', '9', 'available', 9),
('Class 10 — AI, IoT & Smart Applications', 'class-10-ai-iot-smart-applications', 'Integrate AI, IoT and sensor systems into real-world prototypes.', '10', 'available', 10),
('Class 11 — Drones & Autonomous Systems', 'class-11-drones-autonomous-systems', 'Learn drone telemetry, navigation concepts and autonomous-system design.', '11', 'available', 11),
('Class 12 — Engineering & Innovation', 'class-12-engineering-innovation', 'Develop advanced prototypes using engineering, AI, robotics and 3D printing.', '12', 'available', 12)
ON CONFLICT (slug) DO NOTHING;

WITH seed(course_slug, title, slug, description, class_level, difficulty, estimated_time, technology, what_you_build, what_you_learn, components, build_steps, troubleshooting, take_it_further) AS (
  VALUES
  ('class-1-young-makers', 'Mechanical Linkage', 'mechanical-linkage-class-1', 'Build a simple linkage and observe how one movement creates another.', '1', 'Beginner', '60 minutes', 'Mechanical Design', 'A working linkage mechanism.', 'Basic mechanisms, observation and sequencing.', 'Linkage kit or craft materials', 'Assemble the links. Move the input arm. Observe the output. Change one connection and compare.', 'Keep joints free-moving and check alignment.', 'Design a second linkage with a different connection point.'),
  ('class-2-exploring-machines', 'Gear Transmission', 'gear-transmission-class-2', 'Build a small gear train and investigate changes in direction and speed.', '2', 'Beginner', '75 minutes', 'Mechanical Systems', 'A working gear transmission.', 'Rotation, direction and simple mechanical relationships.', 'Gear kit, axles and base', 'Mount the gears. Mesh the teeth. Rotate the input. Test different gear sizes.', 'Ensure gears mesh without excessive pressure.', 'Create a three-gear transmission and predict its output.'),
  ('class-3-electronics-foundations', 'LED Circuit Lab', 'led-circuit-class-3', 'Build and test a safe low-voltage LED circuit.', '3', 'Beginner', '60 minutes', 'Electronics', 'A working LED circuit.', 'Polarity, resistance and complete circuits.', 'LED, resistor, breadboard and battery pack', 'Place the resistor and LED. Connect the power source correctly. Test and observe.', 'Check polarity and every connection if the LED does not light.', 'Add a switch-controlled second LED.'),
  ('class-4-sensors-smart-systems', 'Automatic Night Lamp', 'automatic-night-lamp-class-4', 'Create a light that responds to surrounding brightness.', '4', 'Beginner', '90 minutes', 'Sensors & Electronics', 'An LDR-controlled light prototype.', 'Sensors, changing inputs and automatic responses.', 'LDR, LED, resistor, controller and breadboard', 'Connect the sensor. Add the output. Test in bright and dark conditions. Tune the threshold.', 'Check sensor placement and resistor values.', 'Add a manual override switch.'),
  ('class-5-arduino-foundations', 'Arduino Traffic Signal', 'arduino-traffic-signal-class-5', 'Program a three-light traffic signal using Arduino.', '5', 'Beginner', '90 minutes', 'Arduino & Coding', 'A programmable traffic signal.', 'Digital outputs, timing and sequencing.', 'Arduino Uno, LEDs, resistors, breadboard and jumper wires', 'Wire the LEDs. Program the sequence. Upload and test. Refine timing.', 'Check LED polarity and resistor connections.', 'Add a pedestrian crossing button.'),
  ('class-6-robotics-automation', 'Automated Barrier', 'automated-barrier-class-6', 'Build a barrier that opens when an object is detected.', '6', 'Intermediate', '150 minutes', 'Robotics & Automation', 'A sensor-controlled barrier.', 'Event-driven control, sensors and servo movement.', 'Arduino, distance sensor, servo and LEDs', 'Build the barrier. Connect the sensor and servo. Program detection and opening. Test repeatedly.', 'Check servo power and mechanical movement.', 'Add status lights and an entry counter.'),
  ('class-7-iot-connected-devices', 'IoT Weather Station', 'iot-weather-station-class-7', 'Collect environmental data and display it through a connected dashboard.', '7', 'Intermediate', '180 minutes', 'IoT & Sensors', 'A connected environmental monitor.', 'Sensor data, networking and dashboards.', 'ESP32/ESP8266, temperature-humidity sensor and Wi-Fi', 'Read the sensor. Connect to Wi-Fi. Send readings to a dashboard. Validate the data.', 'Check credentials and sensor pin configuration.', 'Add historical charts and threshold alerts.'),
  ('class-8-advanced-robotics', 'Autonomous Maze Solver', 'autonomous-maze-solver-class-8', 'Develop a robot that detects walls and navigates a maze.', '8', 'Advanced', '240 minutes', 'Robotics & Sensors', 'An autonomous maze-navigation robot.', 'Calibration, feedback and decision logic.', 'Robot chassis, motors, motor driver, sensors and controller', 'Assemble the robot. Calibrate sensors. Implement navigation. Test and tune repeated runs.', 'Calibrate against the actual maze surface and check wheel alignment.', 'Compare multiple navigation strategies.'),
  ('class-9-ai-computer-vision', 'AI Object Detector', 'ai-object-detector-class-9', 'Run a computer-vision model to identify objects in images.', '9', 'Advanced', '240 minutes', 'AI & Computer Vision', 'An object-detection prototype.', 'Inference, confidence scores, datasets and responsible AI basics.', 'Computer, Python, camera/sample images and detection model', 'Load the model. Run inference. Display detections. Test different scenes and record observations.', 'Verify the model environment and image input.', 'Collect a small labelled dataset and evaluate performance.'),
  ('class-10-ai-iot-smart-applications', 'Smart Agriculture Monitor', 'smart-agriculture-monitor-class-10', 'Combine environmental sensors and IoT to monitor growing conditions.', '10', 'Advanced', '240 minutes', 'AI, IoT & Sensors', 'A connected agriculture-monitoring prototype.', 'Sensor fusion, thresholds, dashboards and data-driven decisions.', 'ESP32, soil-moisture, temperature-humidity and light sensors', 'Connect and calibrate sensors. Send data to a dashboard. Define thresholds. Test alerts.', 'Calibrate each sensor for the chosen environment.', 'Build a simple data-based recommendation model.'),
  ('class-11-drones-autonomous-systems', 'Drone Telemetry Lab', 'drone-telemetry-class-11', 'Explore telemetry between a flight controller and ground-control system in simulation or a supervised lab.', '11', 'Advanced', '300 minutes', 'Drones & Embedded Systems', 'A monitored telemetry workflow.', 'Flight data, communication links and system monitoring.', 'Flight simulator or controller, telemetry link and ground-control software', 'Connect the simulated/controller system. Establish telemetry. Inspect flight data. Configure monitoring fields.', 'Use simulation when a controlled flight environment is unavailable.', 'Log telemetry data and build a monitoring dashboard.'),
  ('class-12-engineering-innovation', '3D-Printed Engineering Prototype', '3d-printed-engineering-prototype-class-12', 'Take a digital design through CAD, slicing, printing, testing and iteration.', '12', 'Advanced', '300 minutes', '3D Printing & Product Design', 'A functional 3D-printed prototype component.', 'CAD, tolerances, slicing and engineering iteration.', '3D printer, filament, CAD and slicing software, measuring tools', 'Define the problem. Model the part. Slice it. Print. Test fit/function. Revise and reprint.', 'Check bed adhesion, dimensions and moving-part clearances.', 'Integrate the printed part into a robot, drone or IoT enclosure.')
)
INSERT INTO projects (course_id, title, slug, description, class_level, difficulty, estimated_time, technology, what_you_build, what_you_learn, components, build_steps, troubleshooting, take_it_further, status, sort_order)
SELECT c.id, s.title, s.slug, s.description, s.class_level, s.difficulty, s.estimated_time, s.technology, s.what_you_build, s.what_you_learn, s.components, s.build_steps, s.troubleshooting, s.take_it_further, 'published', s.class_level::int
FROM seed s
JOIN courses c ON c.slug = s.course_slug
ON CONFLICT (slug) DO NOTHING;
